import type { DraftModeConfig } from "@sportverse/draftballer-types";

export const PRESET_MODES: DraftModeConfig[] = [
  {
    id: "all-time-any",
    title: "All-Time · Any League",
    blurb: "Peak-weighted careers across every league.",
    era: "all_time",
    competitionScope: "any_league",
    ratingLens: "club_only",
    blendFactor: 0,
  },
  {
    id: "club-only",
    title: "Club Version",
    blurb: "Ratings from club competitions only.",
    era: "all_time",
    competitionScope: "any_league",
    ratingLens: "club_only",
    blendFactor: 0,
  },
  {
    id: "international",
    title: "International Version",
    blurb: "National team performance only.",
    era: "all_time",
    competitionScope: "international",
    ratingLens: "international_only",
    blendFactor: 1,
  },
  {
    id: "premier-league",
    title: "Premier League",
    blurb: "All-time Premier League legends.",
    era: "all_time",
    competitionScope: "single_league",
    ratingLens: "club_only",
    blendFactor: 0,
    leagueId: "premier-league",
  },
  {
    id: "decade-2010s",
    title: "2010s Decade",
    blurb: "Best of the 2010s across competitions.",
    era: "decade",
    competitionScope: "any_league",
    ratingLens: "blended",
    blendFactor: 0.35,
    decade: "2010s",
  },
  {
    id: "single-year-2020",
    title: "2020 Season",
    blurb: "Single-season ratings for calendar year 2020.",
    era: "single_year",
    competitionScope: "any_league",
    ratingLens: "club_only",
    blendFactor: 0,
    year: 2020,
  },
  {
    id: "continental-cl",
    title: "Champions League",
    blurb: "Continental club competitions only.",
    era: "all_time",
    competitionScope: "continental",
    ratingLens: "club_only",
    blendFactor: 0,
  },
  {
    id: "best-context",
    title: "Best Context",
    blurb: "Peak club or international — whichever shines.",
    era: "all_time",
    competitionScope: "any_league",
    ratingLens: "best_context",
    blendFactor: 0.5,
  },
  {
    id: "ea-current",
    title: "EA FC 26 · Current",
    blurb: "Live EA FC 26 snapshot — exactly as rated today, no prime uplift.",
    era: "all_time",
    competitionScope: "any_league",
    ratingLens: "club_only",
    blendFactor: 0,
    ratingBasis: "ea_current",
  },
  {
    id: "custom",
    title: "Draft Architect",
    blurb: "Build your own era, scope, and rating lens.",
    era: "all_time",
    competitionScope: "any_league",
    ratingLens: "blended",
    blendFactor: 0.35,
  },
];

export function getPresetMode(id: string): DraftModeConfig {
  return PRESET_MODES.find((m) => m.id === id) ?? PRESET_MODES[0]!;
}
